apiVersion: v1
kind: ConfigMap
metadata:
  name: bdd-env
data:
  POSTGRES_DB: "papermerge"
  POSTGRES_USER: "papermerge"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-env
data:
  MINIO_ROOT_USER: "2e8817266261610810596a50b8f4a8c5"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-env
data:
  AWS_REGION_NAME: "us-east-1"
  AWS_S3_ENDPOINT: "http://paperless-minio:9000"
  S3_WORKER_ARGS: "-Q s3,s3preview -c 2"
  PAPERMERGE__S3__BUCKET_NAME: "papermerge"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-env
data:
  OCR_WORKER_ARGS: "-Q ocr -c 2"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-env
data:
  PAPERMERGE__AUTH__USERNAME: "admin"
  PAPERMERGE__DATABASE__URL: "postgresql://papermerge:pmg-secret@papermerge-database:5432/papermerge"
  PAPERMERGE__MAIN__MEDIA_ROOT: "/var/media/pmg"
  PAPERMERGE__OCR__LANG_CODES: "eng,fra"
  PAPERMERGE__OCR__DEFAULT_LANG_CODE: "eng"
  PAPERMERGE__REDIS__URL: "redis://papermerge-redis:6379/0"

---

