---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgre-config
data:
  POSTGRES_USER: "papermerge"
  POSTGRES_DB: "papermerge"

---

apiVersion: v1
kind: Secret
metadata:
  name: postgre-secret
type: Opaque
data:
  POSTGRES_PASSWORD: "cG1nLXNlY3JldA=="

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-deployment
  labels:
    app: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgre-config
            - secretRef:
                name: postgre-secret
          volumeMounts:
            - name: data
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: data
          hostPath:
            path: /data/postgres
            type: DirectoryOrCreate


---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image:  redis:7-alpine
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-deployment
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: LoadBalancer


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  MINIO_ROOT_USER: "2e8817266261610810596a50b8f4a8c5"

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  MINIO_ROOT_PASSWORD: "YTUwMzA3MWRlYmZhM2FjMGMxZGUxY2Q3OWY="

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template: 
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          command: ["minio", "server", "--console-address", ":9001", "/data"]
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
          envFrom:
            - configMapRef:
                name: minio-config
            - secretRef:
                name: minio-secret
      volumes:
        - name: minio-data
          hostPath:
            path: /data
            type: DirectoryOrCreate

      

---

apiVersion: v1
kind: Service
metadata:
  name: minio-service-api
  labels:
    app: minio-api
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: minio-service-console
  labels:
    app: minio-console
spec:
  selector:
    app: minio
  ports:
    - port: 9001
      targetPort: 9001
  type: LoadBalancer
  
---


apiVersion: v1
kind: ConfigMap
metadata:
  name: papers3-config
data:
  AWS_REGION_NAME: "us-east-1"
  AWS_S3_ENDPOINT: "http://paperless-minio:9000"
  PAPERMERGE__MAIN__MEDIA_ROOT: "/var/media/pmg"
  PAPERMERGE__REDIS__URL: "redis://papermerge-redis:6379/0"
  PAPERMERGE__S3__BUCKET_NAME: "papermerge"
  S3_WORKER_ARGS: "-Q s3,s3preview -c 2"

---

apiVersion: v1
kind: Secret
metadata:
  name: papers3-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "MmU4ODE3MjY2MjYxNjEwODExMDU5NmE1MGI4ZjRhOGM1"
  AWS_SECRET_ACCESS_KEY: "YTUwMzA3MWRlYmZhM2FjMGMxZGUxY2Q3OWY="
  PAPERMERGE__DATABASE__URL: "cG9zdGdyZXNxbDovL3BhcGVybWVyZ2U6cG1nLXNlY3JldEBwYXBlcm1lcmdlZGFiYXNlOjU0MzIvcGFwZXJtZXJnZQ=="

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papers3
spec: 
  selector:
    matchLabels:
      app: papers3
  template:
    metadata:
      labels:
        app: papers3
    spec:
      containers:
        - name: papers3
          image: papermerge/s3worker:0.4.3
          volumeMounts:
            - name: papers3-data
              mountPath: "/var/media/pmg" 
          envFrom:
            - configMapRef:
                name: papers3-config
            - secretRef:
                name: papers3-secret
      volumes:
        - name: papers3-data
          hostPath:
            path: /var/media/pmg
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Secret
metadata:
  name: paperocr-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "MmU4ODE3MjY2MjYxNjEwODExMDU5NmE1MGI4ZjRhOGM1"
  AWS_SECRET_ACCESS_KEY: "YTUwMzA3MWRlYmZhM2FjMGMxZGUxY2Q3OWY="
  PAPERMERGE__DATABASE__URL: "cG9zdGdyZXNxbDovL3BhcGVybWVyZ2U6cG1nLXNlY3JldEBwYXBlcm1lcmdlZGFiYXNlOjU0MzIvcGFwZXJtZXJnZQ=="

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: paperocr-config
data:
  AWS_REGION_NAME: "us-east-1"
  AWS_S3_ENDPOINT: "http://paperless-minio:9000"
  PAPERMERGE__REDIS__URL: "redis://papermerge-redis:6379/0"
  PAPERMERGE__S3__BUCKET_NAME: "papermerge"
  OCR_WORKER_ARGS: "-Q ocr -c 2"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperocr
spec: 
  selector:
    matchLabels:
      app: paperocr
  template:
    metadata:
      labels:
        app: paperocr
    spec:
      containers:
        - name: paperocr
          image: papermerge/ocrworker:0.3.1
          envFrom:
            - configMapRef:
                name: paperocr-config
            - secretRef:
                name: paperocr-secret

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-config
data:
  PAPERMERGE__AUTH__USERNAME: "admin"
  PAPERMERGE__MAIN__MEDIA_ROOT: "/var/media/pmg"
  PAPERMERGE__OCR__LANG_CODES: "eng,fra"
  PAPERMERGE__OCR__DEFAULT_LANG_CODE: "eng"
  PAPERMERGE__REDIS__URL: "redis://papermerge-redis:6379/0"

---

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-secret
type: Opaque
data:
  PAPERMERGE__AUTH__PASSWORD: "c2VjcmV0"
  PAPERMERGE__DATABASE__URL: "cG9zdGdyZXNxbDovL3BhcGVybWVyZ2U6cG1nLXNlY3JldEBwYXBlcm1lcmdlZGFiYXNlOjU0MzIvcGFwZXJtZXJnZQ=="
  PAPERMERGE__SECURITY__SECRET_KEY: "OGFhOTEyN2U5MDQzMjRlMWQ5M2MyYjY4NDgzYTMyN2MzYjViZTk2NGRkMTYxZTdlNGRmOGRiY2EwNDQzZWMyMQ=="

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge
spec: 
  selector:
    matchLabels:
      app: papermerge
  template:
    metadata:
      labels:
        app: papermerge
    spec:
      containers:
        - name: papermerge
          image: papermerge/papermerge:3.3.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: papermerge-data
              mountPath: "/var/media/pmg"
          envFrom:
            - configMapRef:
                name: papermerge-config
            - secretRef:
                name: papermerge-secret
      volumes:
        - name: papermerge-data
          hostPath:
            path: /var/media/pmg
            type: DirectoryOrCreate


---

apiVersion: v1
kind: Service
metadata: 
  name: papermerge-service
  labels:
    app: papermerge
spec:
  selector:
    app: papermerge
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
