apiVersion: v1
kind: ConfigMap
metadata:
  name: bdd-env
data:
  POSTGRES_DB: papermerge
  POSTGRES_USER: pmg-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: bdd-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cGFwZXJtZXJnZQ==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdd
  labels:
    app: bdd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdd
  template:
    metadata:
      labels:
        app: bdd
    spec:
      containers:
      - name: bdd
        image: postgres:17-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: bdd-env
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: bdd-env
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bdd-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: bdd-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: bdd-persistent-storage
        hostPath:
          path: /var/lib/postgresql/data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-env
data:
  MINIO_ROOT_USER: 2e8817266261610810596a50b8f4a8c5

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  MINIO_ROOT_PASSWORD: YTUwMzA3MWRlYmZhM2FjMGMxZGUxY2Q3OWY=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: minio-env
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_PASSWORD

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-env
data:
  AWS_REGION_NAME: us-east-1
  AWS_S3_ENDPOINT: http://paperless-minio:9000
  PAPERMERGE__DATABASE__URL: postgresql://papermerge:pmg-secret@papermerge-database:5432/papermerge
  PAPERMERGE__MAIN__MEDIA_ROOT: /var/media/pmg
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  PAPERMERGE__S3__BUCKET_NAME: papermerge
  S3_WORKER_ARGS: "-Q s3,s3preview -c 2"

---

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: MmU4ODE3MjY2MjYxNjEwODEwNTk2YTUwYjhmNGE4YzU=
  AWS_SECRET_ACCESS_KEY: YTUwMzA3MWRlYmZhM2FjMGMxZGUxY2Q3OWY=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
  labels:
    app: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app: s3
    spec:
      containers:
      - name: s3
        image: papermerge/s3worker:0.4.3
        env:
        - name: AWS_REGION_NAME
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: AWS_REGION_NAME
        - name: AWS_S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: AWS_S3_ENDPOINT
        - name: PAPERMERGE__DATABASE__URL
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__DATABASE__URL
        - name: PAPERMERGE__MAIN__MEDIA_ROOT
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__MAIN__MEDIA_ROOT
        - name: PAPERMERGE__REDIS__URL
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__REDIS__URL
        - name: PAPERMERGE__S3__BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__S3__BUCKET_NAME
        - name: S3_WORKER_ARGS
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: S3_WORKER_ARGS
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: papermerge-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: papermerge-secret
              key: AWS_SECRET_ACCESS_KEY
      volumes:
      - name: media
        hostPath:
          path: /var/media/pmg
          type: DirectoryOrCreate

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-env
data:
  AWS_REGION_NAME: us-east-1
  AWS_S3_ENDPOINT: http://paperless-minio:9000
  PAPERMERGE__DATABASE__URL: postgresql://papermerge:pmg-secret@papermerge-database:5432/papermerge
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  PAPERMERGE__S3__BUCKET_NAME: papermerge
  OCR_WORKER_ARGS: "-Q ocr -c 2"

---

apiVersion: v1
kind: Secret
metadata:
  name: ocr-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: MmU4ODE3MjY2MjYxNjEwODEwNTk2YTUwYjhmNGE4YzU=
  AWS_SECRET_ACCESS_KEY: YTUwMzA3MWRlYmZhM2FjMGMxZGUxY2Q3OWY=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
  labels:
    app: ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
      - name: ocr
        image: papermerge/ocrworker:0.4.3
        env:
        - name: AWS_REGION_NAME
          valueFrom:
            configMapKeyRef:
              name: ocr-env
              key: AWS_REGION_NAME
        - name: AWS_S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: ocr-env
              key: AWS_S3_ENDPOINT
        - name: PAPERMERGE__DATABASE__URL
          valueFrom:
            configMapKeyRef:
              name: ocr-env
              key: PAPERMERGE__DATABASE__URL
        - name: PAPERMERGE__REDIS__URL
          valueFrom:
            configMapKeyRef:
              name: ocr-env
              key: PAPERMERGE__REDIS__URL
        - name: PAPERMERGE__S3__BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: ocr-env
              key: PAPERMERGE__S3__BUCKET_NAME
        - name: OCR_WORKER_ARGS
          valueFrom:
            configMapKeyRef:
              name: ocr-env
              key: OCR_WORKER_ARGS
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ocr-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ocr-secret
              key: AWS_SECRET_ACCESS_KEY  

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-env
data:
  PAPERMERGE__AUTH__USERNAME: admin
  PAPERMERGE__DATABASE__URL: postgresql://papermerge:pmg-secret@papermerge-database:5432/papermerge
  PAPERMERGE__MAIN__MEDIA_ROOT: /var/media/pmg
  PAPERMERGE__OCR__LANG_CODES: "eng,fra"
  PAPERMERGE__OCR__DEFAULT_LANG_CODE: "eng"
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  PAPERMERGE__SECURITY__SECRET_KEY: 8aa9127e904324e1d93c2b68483a327c3b5be964dd161e3e4df8dbca0443ec21

---

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-secret
type: Opaque
data:
  PAPERMERGE__AUTH__PASSWORD: c2VjcmV0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge
  labels:
    app: papermerge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge
  template:
    metadata:
      labels:
        app: papermerge
    spec:
      containers:
      - name: papermerge
        image: papermerge/papermerge:3.3.1
        env:
        - name: PAPERMERGE__AUTH__USERNAME
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__AUTH__USERNAME
        - name: PAPERMERGE__DATABASE__URL
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__DATABASE__URL
        - name: PAPERMERGE__MAIN__MEDIA_ROOT
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__MAIN__MEDIA_ROOT
        - name: PAPERMERGE__OCR__LANG_CODES
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__OCR__LANG_CODES
        - name: PAPERMERGE__OCR__DEFAULT_LANG_CODE
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__OCR__DEFAULT_LANG_CODE
        - name: PAPERMERGE__REDIS__URL
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__REDIS__URL
        - name: PAPERMERGE__SECURITY__SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: papermerge-env
              key: PAPERMERGE__SECURITY__SECRET_KEY
        - name: PAPERMERGE__AUTH__PASSWORD
          valueFrom:
            secretKeyRef:
              name: papermerge-secret
              key: PAPERMERGE__AUTH__PASSWORD
        ports:
        - containerPort: 80
      volumes:
      - name: media
        hostPath:
          path: /var/media/pmg
          type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: papermerge
spec:
  selector:
    app: papermerge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer