apiVersion: v1
kind: Secret
metadata:
  name: bdd-secret
type: Opaque
data:
  POSTGRES_PASSWORD: "cG1nLXNlY3JldA=="

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  MINIO_ROOT_PASSWORD: "YTUwMzA3MWRlYmZhM2FjMGMxZGUxY2Q3OWY="

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "MmU4ODE3MjY2MjYxNjEwODEwNTk2YTUwYjhmNGE4YzU="
  AWS_SECRET_ACCESS_KEY: "YTUwMzA3MWRlYmZhM2FjMGMxZGUxY2Q3OWY="

---
apiVersion: v1
kind: Secret
metadata:
  name: papermerge-secret
type: Opaque
data:
  PAPERMERGE__AUTH__PASSWORD: "c2VjcmV0"
  PAPERMERGE__SECURITY__SECRET_KEY: "OGFhOTEyN2U5MDQzMjRlMWQ5M2MyYjY4NDgzYTMyN2MzYjViZTk2NGRkMTYxZTNlNGRmOGRiY2EwNDQzZWMyMQ=="

---

